### ISSUE TITLE
Add mbNET.rokey as new product in Diodes and Unidirectional Security Gateways list

### ISSUE THREAD

**Issue by alexkamm93** [S3cur1tyH4ggis/ICS-Security-Products#14]

**Comment by S3cur1tyH4ggis** [comment]
* [MB connect line GmbH](https://www.mbconnectline.com/en/produkte/mbnetrokey.html)

Pull request rejected - it's not a diode or gateway.
Need to add a secure remote access product category.

Thank you for the contribution @alexkamm93!

**Comment by S3cur1tyH4ggis** [comment]
Added in commit 807057e851714c1bbaa2316ed6f56114aed3caf7
