### ISSUE TITLE
Positive Technologies Industrial Security Incident Manager

### ISSUE THREAD

**Issue by Zzhelezo** [S3cur1tyH4ggis/ICS-Security-Products#17]
[https://www.ptsecurity.com/ww-en/products/isim/](url)

**Comment by Zzhelezo** [comment]
[PT ISIM DS_A4.ENG.0001.01..pdf](https://github.com/S3cur1tyH4ggis/ICS-Security-Products/files/5267233/PT.ISIM.DS_A4.ENG.0001.01.pdf)

**Comment by S3cur1tyH4ggis** [comment]
@Zzhelezo is this product available to purchase now? On the website there is a link to order a pilot. This suggests it is still under development. Thanks.

**Comment by S3cur1tyH4ggis** [comment]
Closing issue. No response from submitter and product website hasn't been updated in a couple of years.
